# Generated by Django 2.2.6 on 2019-11-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.CharField(default='kukhftdgdkg', max_length=100),
        ),
    ]
