# Generated by Django 2.2.7 on 2019-11-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_pizza_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
