# Generated by Django 2.2.7 on 2019-11-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='5748a8bd151146899921116c2d9692df55acafaf9f8d467a972ae6aa3464dc1c', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='2bc76533184643e1b5548a179c157bea595144d8474444afa0f6da28210185b4', max_length=300, null=True),
        ),
    ]
