# Generated by Django 2.2.7 on 2019-11-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191119_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='db2b57e52e244584b88671173c33a23c66fa82e5152e4ff3af6d9308b752a5f9', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='39f11c5618e94afb9e74ca72cb7552d101333e0b47384b20a9857bd0cd97008d', max_length=300, null=True),
        ),
    ]
