# Generated by Django 2.2.7 on 2019-11-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191119_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='3a5682db6c504e81bca5207160bc30fe1e6da5d048ca4b28a80628573dbc20e3', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='533ad5cd23bc46589a1d6ac75780e651ef20274af2a144178692c22f94e74999', max_length=300, null=True),
        ),
    ]
